#!/usr/bin/php
<?php

$package = 'unknown';

$rel = 2;
$maj = 0;
$min = 0;

$out = array();

$control = file_get_contents("debian/control");
$lines = explode("\n", $control);

foreach ($lines as $line) {
    if (preg_match("/Source: (.*)/", $line, $m)) {
        $package = $m[1];
    }
}

$fd = popen("git log --reverse --pretty=format:'%aN|%aE|%cD|%s'", "r");
while ($l = fgets($fd)) {
    $l = trim($l);
    list ($author, $email, $time, $subject) = explode("|", $l);
    $add = array();
    $add[] ="$package ($rel.$maj.$min) uecide; urgency=low";
    $add[] = "";
    $add[] = "  * $subject";
    $add[] = "";
    $add[] = " -- $author <$email>  $time";
    $add[] = "";
    $min++;
    if ($min == 10) {
        $min = 0;
        $maj++;
    }
    $out = array_merge($add, $out);
}
pclose($fd);

file_put_contents("debian/changelog", implode("\n", $out) . "\n");

// Wind back one version point
$min--;
if ($min < 0) {
    $min = 9;
    $maj--;
}

if ($maj < 0) {
    $maj = 9;
    $rel--;
}

$do = false;

if (file_exists("library.json")) {
    $j = json_decode(file_get_contents("library.json"), true);
    $j['version'] = "$rel.$maj.$min";
    file_put_contents("library.json", json_encode($j) . "\n");
    $do = true;
}

if (file_exists("uecide.json")) {
    $j = json_decode(file_get_contents("uecide.json"), true);
    $j['version'] = "$rel.$maj.$min";
    file_put_contents("uecide.json", json_encode($j) . "\n");
    $do = true;
}

if ($do) {
    system("mk15 -c Display");
}
